version: '3'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container_dotnet
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_container_dotnet
    ports:
        - 5672:5672
        - 15672:15672